name: Arventa Connect Github Actions Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      # checks out to latest branch commit
      - name: Checkout
        uses: actions/checkout@v2
      # switches to xcode to test iOS 14
      - name: Switch to Xcode 12
        run: |
          echo "Testing on iOS 14 through Xcode 12"
          sudo xcode-select -switch /Applications/Xcode_12.app
      # builds for all version
      - name: Build Arventa Connect
        run: |
          echo "Build for all (?)"
          mkdir $HOME/Results
          echo "Created folder at: $HOME/Results"
          xcodebuild build-for-testing -scheme "Arventa Connect" \
                                       -workspace "Arventa Connect.xcworkspace" \
                                       -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" \
                                       -derivedDataPath "$HOME/DerivedData/"

      # switches to xcode 10 to test iOS 12
      - name: Switch to Xcode 10
        run: |
          echo "Testing on iOS 12 through Xcode 10.3"
          sudo xcode-select -switch /Applications/Xcode_10.3.app

      # test on iPhone 7 @ 12.4
      - name: Test Arventa Connect (iPhone 7 @ 12.4)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone 7" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Test Results (iPhone 7 @ 12.4)
        run: |
          echo "Current directory: "
          pwd
          cd $HOME/DerivedData/Logs/Test/
          for FILE in *.xcresult; do
            echo "Current file: $FILE"
            cp -r "$FILE" "$HOME/Results/$FILE";
            echo "New location: $HOME/Results/$FILE"
          done

      # test on iPhone SE @ 12.4
      - name: Test Arventa Connect (iPhone SE @ 12.4)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone SE" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Test Results (iPhone SE @ 12.4)
        run: |
          echo "Current directory: "
          pwd
          cd $HOME/DerivedData/Logs/Test/
          for FILE in *.xcresult; do
            echo "Current file: $FILE"
            cp -r "$FILE" "$HOME/Results/$FILE";
            echo "New location: $HOME/Results/$FILE"
          done

      # switches back to xcode 12 to compile
      - name: Switch back to Xcode 12
        run: |
          echo "Switch back to Xcode 12 to compile HTML reports"
          sudo xcode-select -switch /Applications/Xcode_12.app

      # compiles test result
      - name: Compile Test Results
        run: |
          bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh) '2.0.0'
          cd $HOME/Results/
          echo "Raw Results Folder:"
          ls
          count=0
          args=""
          for FILE in *.xcresult; do
            echo "Current file: $FILE"
            count=`expr $count + 1`
            filename="test$count.xcresult"
            args="$args-r $filename "
            mv "$FILE" $filename
            echo "New name: $filename"
          done
          xchtmlreport $args
          echo "Final Results Folder:"
          ls
      - name: Upload Test Result Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: TestResults
          path: "~/Results"
          if-no-files-found: error
          retention-days: 5
