name: iOS Simulator Change Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Arventa Connect
        run: |
          echo "Listing down all xcode versions (?)"
          ls -d /Applications/Xcode*.app
