name: Arventa Connect Github Actions Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: List down all xcode versions
        run: |
            echo "Listing down all xcode versions (?)"
            ls -d /Applications/Xcode*.app

      - name: List down all simulators for Xcode 12
        run: |
            echo "Listing down all simulators for Xcode 12"
            sudo xcode-select -switch /Applications/Xcode_12.app
            instruments -s devices

      - name: List down all simulators for Xcode 11
        run: |
            echo "Listing down all simulators for Xcode 11"
            sudo xcode-select -switch /Applications/Xcode_11.7.app
            instruments -s devices

      - name: List down all simulators for Xcode 10
        run: |
            echo "Listing down all simulators for Xcode 10"
            sudo xcode-select -switch /Applications/Xcode_10.3.app
            instruments -s devices
