name: iOS experimental workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: CompileTestResult
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh) '2.0.0'
          mkdir "$HOME/Results"
          cp -r ./testresultsexp/ $HOME/Results/
          cd $HOME/Results/
          ls
          xchtmlreport -r TestResult.xcresult
          i=0
          j=""
          for FILE in *; do
              i=`expr $i + 1`
              echo "Rename '$FILE' to: test$i.xcresult"
              j="$j-r test$i.xcresult "
              mv "$FILE" "test$i.xcresult"
          done
          echo "j = $j"
          xchtmlreport $j
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: TestResults
          path: "~/Results"
          if-no-files-found: error
          retention-days: 5
