name: Arventa Connect Github Actions Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      # checks out to latest branch commit
      - name: Checkout
        uses: actions/checkout@v2
      # Prepare reusable commands
      - name: Prepare Reusable Shells
        run: |
          mkdir $HOME/Results_iOS13_14
          echo "Created folder at: $HOME/Results_iOS13_14"

          mkdir $HOME/Results_iOS12
          echo "Created folder at: $HOME/Results_iOS12"

          echo "
            echo \"Current directory: \"
            pwd
            cd \$HOME/DerivedData/Logs/Test/
            for FILE in *.xcresult; do
              echo "Current file: \$FILE"
              cp -r "\$FILE" "\$HOME/Results_iOS13_14/\$FILE";
              echo "New location: \$HOME/Results_iOS13_14/\$FILE"
            done
          " >> ~/cp_ios13_14.sh && chmod 755 ~/cp_ios13_14.sh
        
          echo "
            echo \"Current directory: \"
            pwd
            cd \$HOME/DerivedData/Logs/Test/
            for FILE in *.xcresult; do
              echo "Current file: \$FILE"
              cp -r "\$FILE" "\$HOME/Results_iOS12/\$FILE";
              echo "New location: \$HOME/Results_iOS12/\$FILE"
            done
          " >> ~/cp_ios12.sh && chmod 755 ~/cp_ios12.sh

      # Switch to Xcode 12 for building
      - name: Switch to Xcode 12
        run: |
          echo "Testing on iOS 14 through Xcode 12"
          sudo xcode-select -switch /Applications/Xcode_12.app

      # builds for all version
      - name: Build Arventa Connect
        run: |
          xcodebuild build-for-testing -scheme "Arventa Connect" \
                                       -workspace "Arventa Connect.xcworkspace" \
                                       -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" \
                                       -derivedDataPath "$HOME/DerivedData/"
      # test on iPhone 11 Pro Max @ 14.0
      - name: Test Arventa Connect (iPhone 11 Pro Max 14.0)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                           -workspace "Arventa Connect.xcworkspace" \
                                           -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" \
                                           -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 11 Pro Max 14.0)
        run: ~/cp_ios13_14.sh

      # test on iPad Pro 11-inch @ 14.0
      - name: Test Arventa Connect (iPad Pro (11-inch) (2nd generation) 14.0)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPad Pro (11-inch) (2nd generation)" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 11 Pro Max 14.0)
        run: ~/cp_ios13_14.sh

      # switches to xcode 11 to test iOS 13
      - name: Switch to Xcode 11
        run: |
          echo "Testing on iOS 13 through Xcode 11.7"
          sudo xcode-select -switch /Applications/Xcode_11.7.app

      # test on iPhone 11 @ 13.7
      - name: Test Arventa Connect (iPhone 11 13.7)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                           -workspace "Arventa Connect.xcworkspace" \
                                           -destination "platform=iOS Simulator,name=iPhone 11" \
                                           -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 11 13.7)
        run: ~/cp_ios13_14.sh
      # test on iPhone 11 Pro @ 13.7
      - name: Test Arventa Connect (iPhone 11 Pro 13.7)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone 11 Pro" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 11 Pro 13.7)
        run: ~/cp_ios13_14.sh

      # test on iPhone 8 Plus Pro @ 13.7
      - name: Test Arventa Connect (iPhone 8 Plus 13.7)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone 8 Plus" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 8 Plus 13.7)
        run: ~/cp_ios13_14.sh

      # switches to xcode 10 to test iOS 12
      - name: Switch to Xcode 10
        run: |
          echo "Testing on iOS 12 through Xcode 10.3"
          sudo xcode-select -switch /Applications/Xcode_10.3.app

      # test on iPhone 7 @ 12.4
      - name: Test Arventa Connect (iPhone 7 @ 12.4)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone 7" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone 7 @ 12.4)
        run: ~/cp_ios12.sh

      # test on iPhone SE @ 12.4
      - name: Test Arventa Connect (iPhone SE @ 12.4)
        continue-on-error: true
        run: |
          xcodebuild test-without-building -scheme "Arventa Connect" \
                                            -workspace "Arventa Connect.xcworkspace" \
                                            -destination "platform=iOS Simulator,name=iPhone SE" \
                                            -derivedDataPath "$HOME/DerivedData/"
      - name: Copy Results (iPhone SE @ 12.4)
        run: ~/cp_ios12.sh

      # switches back to xcode to test iOS 14
      - name: Switch back to Xcode 12
        run: |
          echo "Switch back to Xcode 12 to compile HTML reports"
          sudo xcode-select -switch /Applications/Xcode_12.app

      # compiles test result for iOS 13 and 14
      - name: Compile Test Results (iOS 13 and 14)
        run: |
          bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh) '2.0.0'
          cd $HOME/Results_iOS13_14/
          echo "Raw Results Folder (iOS 13 and 14):"
          ls
          count=0
          args=""
          for FILE in *.xcresult; do
            echo "Current file: $FILE"
            count=`expr $count + 1`
            filename="test$count.xcresult"
            args="$args-r $filename "
            mv "$FILE" $filename
            echo "New name: $filename"
          done
          xchtmlreport $args
          echo "Final Results Folder:"
          ls
      - name: Upload Test Result Artifact (iOS 13 and 14)
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Test Results for iOS 13 and 14
          path: "~/Results_iOS13_14"
          if-no-files-found: error
          retention-days: 5

      # compiles test result for iOS 12
      - name: Compile Test Results (iOS 13 and 14)
        run: |
          bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh) '1.6.1'
          cd $HOME/Results_iOS12/
          echo "Raw Results Folder (iOS 12):"
          ls
          count=0
          args=""
          for FILE in *.xcresult; do
            echo "Current file: $FILE"
            count=`expr $count + 1`
            filename="test$count.xcresult"
            args="$args-r $filename "
            mv "$FILE" $filename
            echo "New name: $filename"
          done
          xchtmlreport $args
          echo "Final Results Folder:"
          ls
      - name: Upload Test Result Artifact (iOS 12)
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Test Results for iOS 13 and 14
          path: "~/Results_iOS12"
          if-no-files-found: error
          retention-days: 5